### PR TITLE
Change typography setting in user profile #91

### PR DESCRIPTION
**Pull request by vaishnavi-ch**
To solve this issue, we can either delete [this](https://github.com/lacabra/proco-map-app/blob/0511da97f14578f985c523cd6688cb33eaf03e5e/pages/profile.js#L114) div tag (not sure) or give it a [class name and height](https://github.com/vaishnavi-ch/proco-map-app/blob/9c8993db868ca8f37410fe8f9496df55fb0a8ebd/pages/profile.js#L114) . After making the changes I got the following output. @lacabra Kindly let me know if I have to make any other changes or change the className ("mappings-div" - I didnot get any other name 😅)

Screenshot (927)

### CODE REVIEW

**Comment by lacabra** [comment]
Thanks @vaishnavi-ch: this [div](https://github.com/lacabra/proco-map-app/blob/0511da97f14578f985c523cd6688cb33eaf03e5e/pages/profile.js#L114) that you mention cannot be deleted because the ternary operator expects one single html element, that's why that `<div>` is there to act as a wrapper for `<div className="mappings-container">` and `<div className="bottom-button">`. For these cases however, there is the empty `<>` that JSX allows, so the `<div>` that you point out can be replaced by `<>`, which is a simpler solution. Yet, like in the screenshot that you provide, the `Map more schools` button is not anchored at the bottom, there is some white space between that and the black footer. Thoughts?

Also, can you resolve the conflicts that have arisen from the linting introduced in #100? These conflicts need to be resolved before this pull request can be merged. Thanks and sorry for this inconvenience.

**Comment by vaishnavi-ch** [comment]
@lacabra Thank you for your explanation  about the div tag - I've understood clearly.
Here in the screenshot, since there's space between the "what will I recieve for my contribution?" part and the footer,
I thought there must be a bit space between "Map more schools" and the footer. 

image

I actually tested those changes in the google developer tools and not in  the local host as I've been getting few errors, I'll try it once again tomorrow.

**Comment by lacabra** [comment]
@upretiprateek: I would like to get your opinion on the proposed fix above. I had to introduce a required footer in many screens including the profile to comply with Privacy Policy requirements from the OAuth providers (Google, Twitter, Facebook etc), so your design requirement of the `Map More Schools` button to stick to the bottom is very tricky, because we already have a sticky footer, plus given the variable height of the user accomplishments, it is very difficult to calculate the correct height and keep it responsive. 

We have already addressed the spacing of each accomplishment. 

What do you think of the proposed change as it stands now?

**Comment by upretiprateek** [comment]
@lacabra I am not sure what is the proposed fix?
Is it the screenshot that has some whitespace between the button 'Map more schools' and the footer?

**Comment by vaishnavi-ch** [comment]
@lacabra @upretiprateek kindly let me know if it looks fine, I have used   `position: fixed; bottom: 0px;` to position the "map more schools button" at the bottom and it covers the footer, Though I have set the height of the `mappings-container ` and `mappings-div ` to 100% there's still gap between the questions and the button

image

**Comment by lacabra** [comment]
> @lacabra I am not sure what is the proposed fix?
> Is it the screenshot that has some whitespace between the button 'Map more schools' and the footer?

Yes

**Comment by lacabra** [comment]
@vaishnavi-ch: apologies for the confusion since we are working on two different designs, but the black footer must be displayed, so your last proposed solution does not work. Waiting for guidance from @upretiprateek

**Comment by upretiprateek** [comment]
@vaishnavi-ch this looks good! However I am not sure if we can hide the footer, as @lacabra informed me yesterday.
Hence I propose an alternative design, where with a simple CSS mods, we can make the 'Map more schools' button floating.
You can access the design here: https://zpl.io/bJDxEyW

**Comment by lacabra** [comment]
Here's a screenshot of the design @upretiprateek is referring to:

Screen Shot 2021-04-29 at 7 53 28 AM

**Comment by vaishnavi-ch** [comment]
@lacabra @upretiprateek Thank you, However I have a doubt in the design, The following video shows what I have understood from the screenshot, Here we can see that the last part of the "your mappings" will be covered, Is it ok?
P.S I have added more repeated divs in the "your mappings" section  just to show the scrolling part.

https://user-images.githubusercontent.com/66664653/116690876-a8346180-a9d7-11eb-8c69-26388c0cc5a4.mp4

**Comment by lacabra** [comment]
@vaishnavi-ch Thanks for the video, I confirm that this is @upretiprateek's intent, and thus I would ask you to proceed. Thank you 👍

**Comment by vaishnavi-ch** [comment]
created a new pull request #109

**Pull request closed without merging**
