### PR TITLE
Styled profile page

### PR DESCRIPTION
**Pull request by EkkuJ**
#53.

Adding a profile page matching the style guidelines.

## Before

image

## After

Screenshot 2021-03-13 at 18 04 17

## Includes

- A new endpoint `/getAllFacts/[uuid]` for fetching all user facts. The `/getFact/[uuid]` endpoint was implemented to get a random fact, so I wasn't able to use that.
- A new implementation for the `profile.js`-page. On initialization, fetches user stats and facts from `/getUserStats/[uuid]` and `/getAlFacts/[uuid]`. Then displays those stats and facts as the screenshot above describes.

## Testing

Tested through trial and error. Works well, but for me the country-specific facts always give undefined. I'll need the country data to test those facts. @lacabra would you be able to provide the data?

### CODE REVIEW

**Review by lacabra — CHANGES_REQUESTED** [review]
Thanks @EkkuJ, this looks really good.

My one request would be not to duplicate the code from `getFact/[uuid].js` into `getFacts/[uuid].js`. Instead pass an optional parameter that returns them all, vs returning one at random. Copying @CallaJune so that she's aware of this potential change. 

Keeping both files into one, makes the code more maintainable, so that we don't need to update things twice like the queries.

Thanks!

**Review by CallaJune — CHANGES_REQUESTED** [review]
Nice, @EkkuJ. Thanks for putting the profile page together. I see you made some necessary changes to the `getFact/[uuid]` API endpoint. In the game's current state, the endpoint only returns one fact, chosen randomly, and you have altered it to get all facts. I agree that the endpoint should be refactored for greater flexibility, but I think we might want to take it one step further. Instead of returning all facts, perhaps it can either return a random fact -- the current state -- or return a specific fact if passed a fact key. This could be done by editing the current API endpoint and maybe creating a second API endpoint, something like `getSpecificFact/[fact key]` (though I defer to you on naming). 

My reasoning is that all of the facts that exist were not meant to tell a story or be ordered in a specific way. They are simply an exhaustive list of facts that we could display. In the future, we could add facts that are very similar or so many facts that not all would fit on the profile page. We might then want more control over which facts we display on the profile page, and in what order they appear. 

Does that make sense? Happy to talk more and also to brainstorm about implementation.

**Comment by EkkuJ** [comment]
@CallaJune I hear your point! However, I don't see how the ordering/count of the facts would be an issue. Maybe there is a slight misunderstanding with the code; let me clarify.

With these changes, the API would either return

1. A random fact (with `page=result`) or
2. an object containing all the facts (with `page=profile`).

In the latter case, the schema of the return object is as follows:
  `{ "country_count": "You have mapped locations in 4 countries.",`  
  `"top_country": "Your top country is Sierra Leone.",`  
  `"num_countries_mapped_total": "You are part of a global movement! Together, players have mapped locations in 4 countries.",`  
  `"num_locations_mapped_total": "You are part of a global movement! Together, players have mapped 79 locations." }`

From that object, the component in the profile page is able to display any facts in any order. Currently

1. country_count
2. top_country
3. num_locations_mapped_total

When/if the fact API evolves, this implementation makes it reasonably easy to alter the fetched facts from the API code. Also, the display order can be altered from the profile-page code.

With these in mind, do you still see the same issue that you mentioned? If so, could you clarify the problem a bit more?

**Comment by CallaJune** [comment]
@EkkuJ This makes sense. Thank you for the clarification -- my misunderstanding. This sounds good to me.

**Review by lacabra — APPROVED** [review]
Thanks @EkkuJ, everything looks good. Much appreciated 🙏

**Pull request merged**
