### PR TITLE
Improved styling of 'Yes' and 'No' buttons in Test, added HeaderComponent to result.js for uniformity

### PR DESCRIPTION
**Pull request by rachita19082**
This pull request improves the styling and responsiveness of the 'Yes' and 'No' buttons in the Test (quizTest.js) section to make it uniform with the Mapping (quiz.js) section.

**BEFORE**
image

**AFTER**
image

### CODE REVIEW

**Comment by rachita19082** [comment]
@lacabra I made the above changes to make the 'Yes' and 'No' buttons in quiz and test section uniform. Please review and let me know if it is alright.

**Comment by rachita19082** [comment]
@lacabra I have made the following changes in commit 5300fca. The header component was not present in the result.js page and the heading "PROJECT CONNECT" disappeared on hovering over it.

**BEFORE**
image 


**AFTER**
image

**Review by lacabra — CHANGES_REQUESTED** [review]
Good catch @rachita19082! Your pull request looks good to me, but I would like to ask you to resolve the conflicts that exist before we can merge it. The conflicts are probably a result of the linter introduced in #100. Thank you!

**Comment by rachita19082** [comment]
Thank you @lacabra. 
I have resolved the conflicts. Please let me know if anything else is needed.

**Review by lacabra — CHANGES_REQUESTED** [review]
Because of the addition of CI from #96, now the CI build is failing. Would you mind fixing those errors to ensure the CI passes? Thank you

**Comment by rachita19082** [comment]
@lacabra I have looked at the errors and I tried to run `npm run lint:fix`, but that is not fixing the errors automatically. There are 30 errors, some are 'react/no-unescaped-entities' and some are 'Unexpected token ?', none of these problems are due to the changes I made in this pull request. You can view the full error logs [here](https://github.com/lacabra/proco-map-app/pull/101/checks?check_run_id=2449542256). Please let me know if there is a way to fix these automatically or do I have to make the changes manually.

**Comment by lacabra** [comment]
Thanks @rachita19082. I will take care of this, as I agree they are completely out of scope of your PR.

**Comment by rachita19082** [comment]
> Thanks @rachita19082. I will take care of this, as I agree they are completely out of scope of your PR.

Okay, thank you.

**Comment by lacabra** [comment]
@rachita19082: I have updated all the previous errors through merging #106. Now a few new errors appeared, which seem to be the result of mismatched indentation, where the linter is asking to replace tabs with spaces. Now all the errors that the linter points out seem to be pertinent to your code; so I would kindly ask to take a look and fix them. Thank you.

**Comment by rachita19082** [comment]
@lacabra I have resolved all errors in commit 0e32c0f and a416ebc. Please let me know if anything else is required.

**Review by lacabra — APPROVED** [review]
Thanks @rachita19082 for addressing the requested changes. This looks good to me now 👍

**Pull request merged**
