### PR TITLE
Header height on mobile Fixes #90

### LINKED ISSUE #90: Header height in the post signed in state
Once I sign in and go back to the landing page, the header height gets distorted.
(See attached image).

Note: this issue occurred only in the mobile website.

WhatsApp Image 2021-04-20 at 4 16 15 PM

### PR DESCRIPTION
**Pull request by Msgl**
**Description**
The height of the header is not fixed on some mobile devices. It shrinks when the user clicks on "Sign in" and then shrinks once again when the user has been signed in and clicks on "Project connect" to get back to the main page.

**Before**
image

**After**
image

### CODE REVIEW

**Review by lacabra — CHANGES_REQUESTED** [review]
Wow, what a simple fix :)

Thanks @Msgl for your contribution. Take a look at the conflict that GitHub reports, can you please fix it before this PR can be merged? This is due to having implemented the linter in #100 recently. You will need to merge master on your branch, or run the linter in your local environment and push the new changes. Thank you

**Comment by Msgl** [comment]
@lacabra do I need to use git pull to update the master and then merge master to branch? Should I use the following commands to solve this issue? Thank you!

```
git checkout master
git pull
git checkout header-height
git pull
git merge master
git push
```

**Comment by lacabra** [comment]
@Msgl, yes the sequence of commands that you outline above looks correct. When you run `git merge master` the conflicts will come up. It may be easier to discard all of your changes, and accept all changes coming from master, and then reapply your changes, since they are very small :)

**Comment by Msgl** [comment]
@lacabra thanks I will work on it!

**Comment by Msgl** [comment]
Hi @lacabra, I updated my local repository and pushed the changes. Please let me know if everything is ok or if I need to make changes. Thank you

**Comment by lacabra** [comment]
Thanks @Msgl. Please scroll down to the bottom of this page and notice the `This branch has conflicts that must be resolved` section. You can click the `Resolve conflicts` button on the website, or better yet resolve these conflicts on your local repository and push the changes.

The conflicts arise when git anticipates merging your branch to the `master` branch, and identifies changes that have occurred in both branches that cannot be merged automatically. What this means is that you may not have pulled the latest copy of master to your local instance and merged that version to your local branch (or maybe you did, but some recent changes to master were pushed in between that cause a conflict). 

In any case, conflicts have to be resolved before this pull request can be merged. Kindly resolve them. Thank you

**Comment by Msgl** [comment]
@lacabra  I had not set up upstream properly and I was getting an error message that my local is up to date even though it was not. I have since fixed this issue, and then I was able to see the conflicts in VS code, and I created a new commit. At the moment at the bottom of this PR I can see "build Expected — Waiting for status to be reported" and under the report on workflow "1 failing and 1 expected checks". Is this something that will need to be handled from my side? Thank you very much for the feedback, it is the first time I am handling conflicts and it has been very helpful.

**Comment by lacabra** [comment]
Thanks @Msgl. What you were seeing was a result of you being a first-time contributor to this repository, and needing admin approval for the CI to run automatically. I have approved it, and as you can see now the CI passes 🙌

**Review by lacabra — APPROVED** [review]
This looks good to me. Thanks @Msgl for your contribution and addressing the requested changes, so that this can be merged cleanly 🙏

**Pull request merged**
